#Add types for WPF
Add-Type -AssemblyName PresentationFramework
[void][System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")

#sequence id for components over the lifetime of the application.
$_ComponentIdSeq = 0; 

#Constructor for creating a simple component,
#whether or not the component is a top-level component or a child component.
Function New-SimpleComponent([ScriptBlock] $ComponentDefScript, $Props) {
    _Log "New-SimpleComponent: ComponentDefScript: $($ComponentDefScript)"
    _Log "New-SimpleComponent: Props: $($Props | out-string)"
    $ComponentId = $script:_ComponentIdSeq++
    $NewComponent = New-Module -AsCustomObject -ArgumentList @($ComponentId, $ComponentDefScript, $Props) -ScriptBlock $_SimpleComponentDef

    _Log "Defining component $($NewComponent)"
    $NewComponent._DefineComponent()

    _Log "New-SimpleComponent: Return"
    return $NewComponent
}

$_SimpleComponentDef = {
    param($_ComponentId, [ScriptBlock] $_ComponentDefScript, $Props)

    $ErrorActionPreference = "Stop"

    $Refs = @{};            #map of ref WPF components directly relating to this component, eg MyButton1 => [WPF object]
                            #This map will NOT contain grandchild WPF components.
                            #This map will only be populated after _RealizeWpf has been called.
    $_Refs = @{};           #map of short name => full name
    $_Children = @{};       #map of child component objects, eg _SomeComponent123 => [SimpleComponent object]
                            #this will only be populated after _RealizeXaml has been called.
    [xml] $_Xaml = $null;   #the actual xaml used for this component
    [ScriptBlock] $_XamlScript = $null;   #the script to be executed to obtain the pre-realized xaml
    [ScriptBlock] $_InitScript = $null;   #the actual init script to call to initialize the component
    [String] $_XamlNamePrefix = "_SimpleComponent_$($_ComponentId)_";       #the prefix for all refs belonging to this component, eg "_SimpleComponent_1_MyButton1"
    [String] $_XamlPlaceholder = "<_SimpleComponent_$($_ComponentId)/>";    #the xaml placeholder for this component, eg "<_SomeComponent123 />"
                                                                            #this will be autogenerated.
    $Wpf = $null;           #the WPF component that this component represents.
                            #This will only be populated after the component _RealizeWpf has been called.

    #Add a component to the children of this component.
    #The child component object will contain its definition script.
    function _AddComponentAsChild($Component) {
        _Log "_AddComponentAsChild: Component: $($Component)"
        $_Children[$Component.$_XamlPlaceholder] = $Component
    }

    #Convenience method to create a component object and 
    #add it as a child to this component object.
    function AddChild([ScriptBlock] $_ComponentDefScript, $_Props) {
        _Log "AddChild: _ComponentDefScript: $($_ComponentDefScript)"
        _Log "AddChild: _Props: $($_Props | out-string)"
        $ChildComponent = New-SimpleComponent $_ComponentDefScript $_Props
        _AddComponentAsChild $ChildComponent
    }

    #Run the definition script.
    #The result of this will be that the Xaml script and the Init script 
    #will have opportunity to be defined by the custom component.
    function _DefineComponent() {
        try {
            _Log "_DefineComponent: $($this)"
            &$this._ComponentDefScript $this
            _Log "_DefineComponent: $($this) Complete"
        } catch {
            _Throw "_DefineComponent: Error: $($_ | out-string)"
        }
    }

    #Realize the xaml in this component by resolving the placeholders 
    #for each of this component's child components.
    #The result will be that this component and each of its children
    #will have valid xaml and no remaining placeholders.
    function _RealizeXaml() {
        try {
            _Log "_RealizeXaml: $($this)"

            #Assert that we have a xaml script to run
            if (-not($this._XamlScript)) { _Throw "_RealizeXaml: Error. No xaml provided. Must provide a XAML script." }

            #Run the xaml script
            $this._Xaml = &$this._XamlScript $this

            #Add a name attribute for the root node if it does not already exist.
            _Log "_RealizeXaml: $($this) Checking if need to create root node Name attribute"
            $RootNode = $this._Xaml.SelectSingleNode("/*")
            $RootNodeNameAttribute = $this._Xaml.SelectSingleNode("/*/@Name")
            if (-not($RootNodeNameAttribute)) {
                _Log "_RealizeXaml: $($this) Creating root node Name attribute"
                $RootNodeNameAttribute = $RootNode.OwnerDocument.CreateAttribute("Name")
                $RootNodeNameAttribute.Value = "this"
                $RootNode.Attributes.Append($RootNodeNameAttribute) | out-null

                _Log "_RealizeXaml: $($this) Added root node Name attribute: $($RootNodeNameAttribute.Value)"
            }

            #Create a ref mapping for "this". It will point to the root node. 
            #The root node is guaranteed to have a Name attribute due to setup above.
            $this._Refs["this"] = $RootNodeNameAttribute.Value

            #Find and store the name attributes that are present in this component
            $this._Xaml.SelectNodes("//@Name") | % {

                #TODO Prepend any name attributes that do not begin with _ with this component's XamlNamePrefix
                #This will help later so that those WPF components can be traced to this component for use during the init process.
                if (-not($_.Value.StartsWith("_"))) {
                    $newName = $this._XamlNamePrefix + $_.Value
                    _Log "_RealizeXaml: Replace original Name $($_.Value) with unique Name $($newName)"
                    $_.Value = $newName
                }

                #Name attribute will be something like _SimpleComponent_1_MyButton1
                #The short name should be MyButton1
                #In the case of the name being something like MyButton2
                #The conversion to short name will be a noop.
                $shortName = $_.Value -replace $this._XamlNamePrefix, ""
                $this._Refs[$shortName] = $_.Value
            }

            #TODO use child component map to replace xaml placeholders with child component xaml.

            _Log "_RealizeXaml: $($this) Complete"
        } catch {
            _Throw "_RealizeXaml: Error: $($_ | out-string)"
        }
    }

    #Realize the WPF component by loading the XAML as WPF object.
    #The result of this is that this component's WPF variable will contain the WPF object created.
    #This action will also create all of the "child" WPF components.
    #This method will then inspect all the WPF elements by their IDs to 
    #fill in the child component's WPF variable as well as the
    #child component's children map.
    function _RealizeWpf() {
        try {
            _Log "_RealizeWpf: $($this)"

            #Load WPF component
            $WpfComponent = [Windows.Markup.XamlReader]::Load((New-Object System.Xml.XmlNodeReader $this._Xaml))
            $this.Wpf = $WpfComponent

            #TODO Find refs inside the xaml that belong to this component
            #(by using this component ID to identify name attributes)
        

            _Log "_RealizeWpf: $($this) Complete"
        } catch {
            _throw "_RealizeWpf: Error: $($_ | out-string)"
        }
    }

    #Find refs inside the xaml that belong to this component
    #AND to its children, recursively
    #(by using this component ID to identify name attributes)
    #The result will be a populated $refs variable.
    function _InitRefsDeep() {
        $this._InitRefs()
        $this._Children.Keys | % {
            $this.Children[$_]._InitRefs()
        }
    }

    #Find refs inside the xaml that belong to this component
    #(by using this component ID to identify name attributes)
    #The result will be a populated $refs variable.
    function _InitRefs() {
        try {
            _Log "_InitRefs: $($this) XamlNamePrefix: $($this._XamlNamePrefix)"
            _Log "_InitRefs: $($this) _Refs: $($this._Refs | out-string)"

            #At this point the _Refs table will be filled out.
            #eg: MyButton1 => _SimpleComponent_1_MyButton1
            #eg: MyButton2 => MyButton2
            #Use this table to discover which actual name to use to find the WFP component ref.
            $this._Refs.Keys | % {
                $actualName = $this._Refs[$_]
                $this.Refs[$_] = $this.Wpf.FindName($actualName)
            }

            _Log "_InitRefs: $($this) Refs: $($this.Refs | out-string)"
            _Log "_InitRefs: $($this) Complete"
        } catch {
            _Throw "_InitRefs: Error: $($_ | out-string)"
        }
    }

    #Initialize this component by calling its init script
    #and then calling each child's init script (if not $null).
    #The result will be that this component and each of its children
    #will have had their init scripts called.
    #This means that the WPF objects are fully initialized,
    #ready to be displayed.
    function _Init() {
        try {
            _Log "_Init: $($this)"
            if ($this._InitScript) {
                _Log "_Init: $($this) Calling init function: $($this._InitScript)"
                &$this._InitScript $this
            }
        } catch {
            _Throw "_Init: $($this) Error calling init function, Check your Init function for the following error: $($_ | out-string)"
        }
    }

    #Assign the script that will be called to generate xaml.
    function Xaml([ScriptBlock] $XamlScript) {
        try {
            $this._XamlScript = $XamlScript
        } catch {
            _Throw "Xaml: Error: $($_ | out-string)"
        }
    }

    #Assign the script that will be called to initialize the wpf objects.
    function Init([ScriptBlock] $InitScript) {
        try {
            $this._InitScript = $InitScript
        } catch {
            _Throw "Init: Error: $($_ | out-string)"
        }
    }

    #String representation of this component.
    function ToString() {
        return "Framework.SimpleComponent[$($this._XamlPlaceholder)]"
    }

    Export-ModuleMember -Function *
    Export-ModuleMember -Variable *
}

#Log the activities of this component.
#Only log when in debug mode, ie, when $env:DEBUG is not empty.
Function _Log($msg) {
    if ($env:DEBUG) {
        write-host $msg
        $msg >> stuff.txt
    }
}

Function _Throw($msg) {
    _Log $msg
    throw $msg
}